config/routes.rb
Rails.application.routes.draw do
  root to: "boxes#index"

  resources :boxes, only: [:show] do
    resources :pokemons, only: [:new, :create]
  end

  resources :pokemons, only: [:destroy] do
    resources :taggings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :pokemons, dependent: :destroy

  validates :name, :banner_url, presence: true, uniqueness: true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :box

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :name, presence: true
end

# Pokemon id: 5  name: "Flareon"

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :pokemons, through: :taggings

  validates :name, uniqueness: true, presence: true
end

# Tag id: 1 name: "Fire"

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :pokemon
  belongs_to :tag

  validates :tag, uniqueness: { scope: :pokemon }
end

# Tagging pokemon_id: 5 tag_id: 1
# Tagging pokemon_id: 4 tag_id: 2
# Tagging pokemon_id: 4 tag_id: 5
# Tagging pokemon_id: 5 tag_id: 1

# Doctor first_name: John last_name: Doe
# Doctor first_name: John last_name: Hills
# Doctor first_name: John last_name: Doe

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def index
    @boxes = Box.all
  end

  def show
    @box = Box.find(params[:id])
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def new
    @box     = Box.find(params[:box_id])
    @pokemon = Pokemon.new
  end

  def create
    @box     = Box.find(params[:box_id])
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.box = @box

    if @pokemon.save
      redirect_to @box
    else
      render :new
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    redirect_to @pokemon.box
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def new
    @pokemon = Pokemon.find(params[:pokemon_id])
    @tagging = Tagging.new
  end

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @tagging = Tagging.new(tagging_params)
    @tagging.pokemon = @pokemon

    if @tagging.save
      redirect_to @pokemon.box
    else
      render :new
    end
  end

  private

  def tagging_params
    params.require(:tagging).permit(:tag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/boxes/index.html.erb
<div class="container">
  <h1>Pokemon Boxes</h1>
  <ul>
    <% @boxes.each do |box| %>
      <li><%= link_to box.name, box %></li>
    <% end %>
  </ul>
</div>

app/views/boxes/show.html.erb
<div
  class="banner mb-5"
  style="
    background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @box.banner_url %>);
  ">
  <div class="container">
    <h1><%= @box.name %></h1>
    <p><%= link_to "Add Pokemon", new_box_pokemon_path(@box), class: "btn btn-primary" %></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @box.pokemons.each do |pokemon| %>
      <div class="col-4">
        <%= render "pokemons/card", pokemon: pokemon %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonBoxes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_card.html.erb
<div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.pokemondb.net/artwork/<%= pokemon.name.downcase %>.jpg)">
  <%= pokemon.name %>

  <div class="card-tags">
    <% pokemon.tags.each do |tag| %>
      <span><%= tag.name %></span>
    <% end %>
    <%= link_to "Add tag", new_pokemon_tagging_path(pokemon), class: "new-tag" %>
  </div>

  <%= link_to "x", pokemon_path(pokemon), method: :delete, "data-confirm": "Are you sure? He's gonna miss you." %>
</div>

app/views/pokemons/new.html.erb
<%# POST boxes/5/pokemons %>

<div class="row justify-content-center">
  <div class="col-sm-4">
    <h1>New pokemon for <%= @box.name %></h1>
    <%= simple_form_for [@box, @pokemon] do |f| %>
      <%= f.input :name %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/taggings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Tagging <%= @pokemon.name %></h1>
      <%= simple_form_for [@pokemon, @tagging] do |f| %>
        <!-- This: -->
        <%= f.association :tag %>
        <!-- Does this: -->
        <%#= f.association :tag, collection: Tag.all %>

        <!-- So if you want to change the available tags for selection, you -->
        <!-- Need to update the Tag.all with a different query. -->
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>